id: 4d27a4378a504ace80fcc3a52414d120
initial_creation_type: ocr
source_metadata:
  volumes:
    62a3dfe78af1426bb70289f9a6992d7d:
      base_file: v096.txt
      image_group_id: I1PD95942
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
